var inventory =  [
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 0,
        slotId: "cell0",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 1,
        slotId: "cell1",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 2,
        slotId: "cell2",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 3,
        slotId: "cell3",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 4,
        slotId: "cell4",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 5,
        slotId: "cell5",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 6,
        slotId: "cell6",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 7,
        slotId: "cell7",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 8,
        slotId: "cell8",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 9,
        slotId: "cell9",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 10,
        slotId: "cell10",
        itemAmount: 0,
        empty: true,
      },
        {
          item: "empty",
          itemNumber: 0,
          slotNumber: 11,
          slotId: "cell11",
          itemAmount: 0,
          empty: true,
        },
        {
          item: "empty",
          itemNumber: 0,
          slotNumber: 12,
          slotId: "cell12",
          itemAmount: 0,
          empty: true,
        },
        {
          item: "empty",
          itemNumber: 0,
          slotNumber: 13,
          slotId: "cell13",
          itemAmount: 0,
          empty: true,
        },
        {
          item: "empty",
          itemNumber: 0,
          slotNumber: 14,
          slotId: "cell14",
          itemAmount: 0,
          empty: true,
        },
        {
          item: "empty",
          itemNumber: 0,
          slotNumber: 15,
          slotId: "cell15",
          itemAmount: 0,
          empty: true,
        },
        {
          item: "empty",
          itemNumber: 0,
          slotNumber: 16,
          slotId: "cell16",
          itemAmount: 0,
          empty: true,
        },
        {
          item: "empty",
          itemNumber: 0,
          slotNumber: 17,
          slotId: "cell17",
          itemAmount: 0,
          empty: true,
        },
        {
          item: "empty",
          itemNumber: 0,
          slotNumber: 18,
          slotId: "cell18",
          itemAmount: 0,
          empty: true,
        },
        {
          item: "empty",
          itemNumber: 0,
          slotNumber: 19,
          slotId: "cell19",
          itemAmount: 0,
          empty: true,
        },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 20,
        slotId: "cell20",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 21,
        slotId: "cell21",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 22,
        slotId: "cell22",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 23,
        slotId: "cell23",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 24,
        slotId: "cell24",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 25,
        slotId: "cell25",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 26,
        slotId: "cell26",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 27,
        slotId: "cell27",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 28,
        slotId: "cell28",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 29,
        slotId: "cell29",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 30,
        slotId: "cell30",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 31,
        slotId: "cell31",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 32,
        slotId: "cell32",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 33,
        slotId: "cell33",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 34,
        slotId: "cell34",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 35,
        slotId: "cell35",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 36,
        slotId: "cell36",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 37,
        slotId: "cell37",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 38,
        slotId: "cell38",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 39,
        slotId: "cell39",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 40,
        slotId: "cell40",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 41,
        slotId: "cell41",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 42,
        slotId: "cell42",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 43,
        slotId: "cell43",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 44,
        slotId: "cell44",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 45,
        slotId: "cell45",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 46,
        slotId: "cell46",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 47,
        slotId: "cell47",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 48,
        slotId: "cell48",
        itemAmount: 0,
        empty: true,
      },
      {
        item: "empty",
        itemNumber: 0,
        slotNumber: 49,
        slotId: "cell49",
        itemAmount: 0,
        empty: true,
      }
    ]



    var cInventory = [
          {
            item: "empty",
            itemNumber: 0,
            slotNumber: 0,
            slotId: "c-cell0",
            itemAmount: 0,
            empty: true,
          },
          {
            item: "empty",
            itemNumber: 0,
            slotNumber: 1,
            slotId: "c-cell1",
            itemAmount: 0,
            empty: true,
          },
          {
            item: "empty",
            itemNumber: 0,
            slotNumber: 2,
            slotId: "c-cell2",
            itemAmount: 0,
            empty: true,
          },
          {
            item: "empty",
            itemNumber: 0,
            slotNumber: 3,
            slotId: "c-cell3",
            itemAmount: 0,
            empty: true,
          },
        ]



      var outSlot = [
        {
          item: "empty",
          itemNumber: 0,
          slotNumber: 0,
          slotId: "c-out",
          itemAmount: 0,
          empty: true,
        },
      ]



    var possibleItems = [
      {
        itemName: "empty",
        itemImage: " ",
        itemNumber: 0,
      },
//BLOCK ITEMS
      {
        itemName: "Grass",
        itemImage: "<img src='data/images/grass.png'>",
        itemNumber: 1,
      },
      {
        itemName: "Dirt",
        itemImage: "<img src='data/images/dirt.png'>",
        itemNumber: 2,
      },
      {
        itemName: "Sand",
        itemImage: "<img src='data/images/sand.png'>",
        itemNumber: 3,
      },
      {
        itemName: "Coal Block",
        itemImage: "<img src='data/images/coal_block.png'>",
        itemNumber: 4,
      },
      {
        itemName: "Wooden Planks",
        itemImage: "<img src='data/images/wooden_planks.png'>",
        itemNumber: 5,
      },
//HANDHELD / ITEM ITEMS
      {
        itemName: "Coal Lump",
        itemImage: "<img src='data/images/coal_lump.png'>",
        itemNumber: 6,
      },
      {
        itemName: "Iron Chunk",
        itemImage: "<img src='data/images/iron_chunk.png'>",
        itemNumber: 7,
      },
      {
        itemName: "Iron Ingot",
        itemImage: "<img src='data/images/iron_ingot.png'>",
        itemNumber: 8,
      },
      {
        itemName: "Leaves",
        itemImage: "<img src='data/images/leaves.png'>",
        itemNumber: 9,
      },
    ]
